# Preprocessing coordinates data

In [53]:
# import csv

# output_file = 'output123.csv'

# def process_data(row):
#     return [field.replace(',', '.') for field in row]

# # Read the CSV file and process the data
# with open("T:\Python\AYD\MAIN.csv", 'r', newline='') as csvfile:
#     reader = csv.reader(csvfile, delimiter=';')
#     data = [process_data(row) for row in reader]

# # Write the processed data to a new CSV file
# with open(output_file, 'w', newline='') as csvfile:
#     writer = csv.writer(csvfile)
#     writer.writerows(data)

# CONNECT MYSQL, GET ELEVATION


In [54]:
import requests, json
import pandas as pd

try:
  file=open("T:\Python\AYD\coordinates.csv","r")
  coordinate=file.readlines() 

except FileNotFoundError:
  print("File coordinate.txt not found!")

apikey= "AIzaSyAJD8Axs5XIOU8YTkZwyeLd_oiCwungmbI"
value = []    
a = 0
for latlng in coordinate:
  serviceURL = "https://maps.googleapis.com/maps/api/elevation/json?locations="+latlng+"&key="+apikey
  
  r = requests.get(serviceURL)
  print(r.text)
  y = json.loads(r.text)
  for result in y["results"]:
    if result["elevation"] > 0:
          value.append((result["location"]["lat"], result["location"]["lng"],(result["elevation"])))
    else:
          a +=1


# Make a polygon to check if points are in or out of the polygon

In [55]:
import shapely.geometry
import pandas as pd
file=open("T:\Python\AYD\coordinates.csv","r")
coordinate=file.readlines() 

polygon = shapely.geometry.Polygon(
    [   
        
        (16.116005902735022, 108.21932775720553),
        (16.119271033481184, 108.21872084260775),
        (16.120670358768827, 108.22175541559662),
        (16.11670557813556, 108.22527552026372),
        (16.11612251547321, 108.22915977368946),
        (16.112274258906716, 108.24178359732318),
        (16.105860332050057, 108.25501433555465),
        (16.108192693080934, 108.26059794985417),
        (16.099679442741323, 108.26933752006212),
        (16.09793009950126, 108.28050474866119),
        (16.104344282678404, 108.28705942631713),
        (16.105277237508588, 108.29349272105354),
        (16.103411323462186, 108.30004739870951),
        (16.09594749186185, 108.30465994965259),
        (16.099562820338246, 108.30987941519345),
        (16.111574567872385, 108.31060771271078),
        (16.11285733288319, 108.31667685868852),
        (16.11670557813556, 108.32068249503384),
        (16.116239128142833, 108.32930068232223),
        (16.117988309957685, 108.33816163544974),
        (16.12906610303965, 108.33015036275911),
        (16.13641208745076, 108.32626610933336),
        (16.14317481632265, 108.32116802671206),
        (16.14434078071058, 108.31582717825164),
        (16.14095946506474, 108.31206430774543),
        (16.135945683842092, 108.31206430774543),
        (16.130931775681926, 108.30975803227389),
        (16.125917740619425, 108.31000079811301),
        (16.1242852367088, 108.30320335461792),
        (16.133147239124014, 108.29519208192733),
        (16.138860688373974, 108.2858455971216),
        (16.133730251700946, 108.27492113436166),
        (16.147255661630293, 108.26472496911906),
        (16.154134610362437, 108.25877720606084),
        (16.156349814121015, 108.24991625293336),
        (16.149704128423497, 108.23838487557563),
        (16.147022472741142, 108.23352955883082),
        (16.134313262566337, 108.2279459445313),
        (16.128716287467856, 108.22054158643846),
        (16.124518452381032, 108.22090573519712),
        (16.124518452381032, 108.21471520629983),
        (16.116005902735022, 108.21932775720553),
        (16.116005902735022, 108.21932775720553)
    ]
)

lst = []
for line in coordinate:
    latitude, longitude = map(float, line.strip().split(','))
    point = shapely.geometry.Point(latitude, longitude)
    
    if polygon.contains(point):
        lst.append((latitude, longitude))

    else:
        pass

df = pd.DataFrame(lst)
# df.to_csv("point_in_polygon.csv", index = False)


# Check to get the coordinates inside the polygon to find set of landslide

In [56]:
import shapely.geometry
import pandas as pd
file=open("LATLONONLY.csv","r")
coordinate=file.readlines() 

polygon = shapely.geometry.Polygon(
    [   
        (16.105402336539584, 108.28278771665903),
        (16.105926336240977, 108.28606015199594),
        (16.104973608481977, 108.2862832725871),
        (16.104497242887167, 108.28358103431646),
        (16.130390795772456, 108.24377650913769),
        (16.130060988706056, 108.2503425560838),
        (16.125072589879853, 108.25060004812089),
        (916.123753322912986, 108.23686713947546)
        
    ]
)

lst = []
for line in coordinate:
    latitude, longitude = map(float, line.strip().split(','))
    point = shapely.geometry.Point(latitude, longitude)
    
    if polygon.contains(point):
        lst.append((latitude, longitude))

    else:
        pass

df = pd.DataFrame(lst)
df.to_csv('LATLONONLY.csv', index = False)


# Calculate slope based on lat,lon,elevation


In [57]:
import csv
from math import sin, cos, sqrt, atan2, radians, atan, pow

df = pd.read_csv('combine_all_check.csv')

csv_data = pd.read_csv('combine_all_check.csv')

data_lat_lon_num = csv_data[['lat_by_num', 'long_by_num']].values.tolist()
data_lat_lon = csv_data[['lat', 'lon']].values.tolist()
data_ele = csv_data['elevation'].values.tolist()
last = []
slope = []

R = 6373000
for index, row in df.iterrows():
    lat_num = int(row['lat_by_num'])
    long_num = int(row['long_by_num'])
    value = [[lat_num, long_num+1], [lat_num, long_num-1], [lat_num+1, long_num], [lat_num-1, long_num]]
    
    idx = data_lat_lon_num.index([lat_num, long_num])
    results = [[data_ele[idx],data_lat_lon[idx]]]
    
    for i in value:
        if i in data_lat_lon_num: 
            ind = data_lat_lon_num.index(i)
            results.append([data_ele[ind], data_lat_lon[ind]])
        else: 
            results.append(None)
    last.append(results)
slope_degrees = []

for i in last:

    if None in i:
        pass
    else:
    
        slat1, slon1, elat1, elon1 = radians(float(i[0][1][0])), radians(float(i[0][1][1])), radians(float(i[1][1][0])), radians(float(i[1][1][1]))

        dlon1 = elon1 - slon1
        dlat1 = elat1 - slat1
        
        a_1 = sin(dlat1 / 2)**2 + cos(slat1) * cos(elat1) * sin(dlon1 / 2)**2
        c1 = 2 * atan2(sqrt(a_1), sqrt(1 - a_1))

        distance_rigth_long = R * c1
        ######################################################################################################################
        slat2, slon2, elat2, elon2 = radians(float(i[0][1][0])), radians(float(i[0][1][1])), radians(float(i[2][1][0])), radians(float(i[2][1][1]))

        dlon2 = elon2 - slon2
        dlat2 = elat2 - slat2
        
        a_2 = sin(dlat2 / 2)**2 + cos(slat2) * cos(elat2) * sin(dlon2 / 2)**2
        c2 = 2 * atan2(sqrt(a_2), sqrt(1 - a_2))

        distance_left_long = R * c2
        ##########################################################################################################################
        slat3, slon3, elat3, elon3 = radians(float(i[0][1][0])), radians(float(i[0][1][0])), radians(float(i[3][1][0])), radians(float(i[3][1][1]))

        dlon3 = elon3 - slon3
        dlat3 = elat3 - slat3
        
        a_3 = sin(dlat3 / 2)**2 + cos(slat3) * cos(elat3) * sin(dlon3 / 2)**2
        c3 = 2 * atan2(sqrt(a_3), sqrt(1 - a_3))

        distance_up_lat = R * c3
        ##########################################################################################################################
        slat4, slon4, elat4, elon4 = radians(float(i[0][1][0])), radians(float(i[0][1][0])), radians(float(i[4][1][0])), radians(float(i[4][1][1]))

        dlon4 = elon4 - slon4
        dlat4 = elat4 - slat4
        
        a_4 = sin(dlat4 / 2)**2 + cos(slat4) * cos(elat4) * sin(dlon4 / 2)**2
        c4 = 2 * atan2(sqrt(a_4), sqrt(1 - a_4))

        distance_down_lat = R * c4

        dz_dx = (i[1][0] - i[2][0]) / (distance_rigth_long + distance_left_long)
        dz_dy = (i[3][0] - i[4][0]) / (distance_up_lat + distance_down_lat)
        
        rise_run = sqrt(pow(dz_dx, 2) + pow(dz_dy, 2))
        
        slope = atan(rise_run) * 57.29578
        
        slope_degrees.append((i[0][1][0], i[0][1][1], slope))

ka = pd.DataFrame(slope_degrees)
ka.to_csv('slope_check.csv', index = False)


In [58]:
# df = pd.read_csv('last.csv')
# max_value_column = df["slope"].max()
# max_value_column

# Processing data

In [59]:
# df = pd.read_csv('last.csv')
# df.drop(['lat_by_num','long_by_num', 'elevation'], axis = 1, inplace=True)
# df.to_csv('last.csv', index = False)

In [60]:
# import pandas as pd 

# df = pd.read_csv('lat_lon_NDVI_slope.csv')
# df = df[['lat', 'lon']]
# df.to_csv('LATLON.csv', index = False)

In [61]:
# import pandas as pd 

# df = pd.read_csv("combine_all_check.csv")

# df['lat_by_num'] = df['lat_by_num'].astype(int)
# df['long_by_num'] = df['long_by_num'].astype(int)
# df.to_csv('combine_all_check.csv', index = False)

In [62]:
# import pandas as pd 

# df = pd.read_csv('test_round.csv')

# df['lat'] = df['lat'].round(8)
# df['lon'] = df['lon'].round(7)

# df.to_csv('test_round.csv', index = False)

In [63]:
# import pandas as pd
# df = pd.read_csv('test.csv')

# df['lat'], df['lon'], df['NDVI'] = df['lon'], df['lat'], df['NDVI']
# df.to_csv('test.csv', index = False)

#### Check duplicates 

In [64]:
# import pandas as pd

# df1 = pd.read_csv('LATLONONLY.csv')

# df2 = pd.read_csv('lat_lon_NDVI_slope.csv')

# df3 = pd.merge(df1, df2, how = 'right', on = ['lat', 'lon'])

# df3['Target'] = df3['Target'].fillna(0)


# df3 = df3.drop_duplicates(subset = ['NDVI', 'slope'])
# df3.to_csv('LATLONLY.csv',index=False)




### Merge rain data

In [65]:
# import pandas as pd
# df = pd.read_csv('rain.csv')

# # df1 = pd.read_csv('LATLON.csv')

# df2 = pd.read_csv('test.csv')
# df2_round = pd.read_csv('test_round.csv')
# last = pd.read_csv('LATLONLY.csv')

# df3 = pd.merge(df, df2_round, how = 'left', on = ['lat','lon'])

# df4 = pd.merge(df3, df2, how = 'left', on = 'NDVI')

# # df5 = pd.merge(df4,df2, how = 'left', on = 'NDVI')

# df4.drop(['lat_x', 'lon_x'], axis = 1, inplace=True)
# df4 = df4.rename({'lat_y': 'lat', 'lon_y': 'lon'}, axis = 1)

# df5 = pd.merge(df4, last, how = 'right', on = 'NDVI')
# df5 = df5.drop_duplicates(subset = ['NDVI', 'slope'])
# df5.drop(['lat_x', 'lon_x'], axis = 1, inplace=True)
# df5 = df5.rename({'lat_y': 'lat', 'lon_y': 'lon'}, axis = 1)
# df5.drop('time', axis=1, inplace=True)
# df5 = df5[['lat', 'lon', 'NDVI', 'slope','precipitation_sum (mm)', 'Target']]
# df5.to_csv('Thu.csv', index = False)



In [66]:
# import pandas as pd 

# df = pd.read_csv('Thu.csv')

# df['precipitation_sum (mm)'] = df['precipitation_sum (mm)'].fillna(method='ffill')

# df.to_csv('Thu.csv', index = False)

In [67]:
# df = pd.read_csv('output.csv')

# df = df[df['time'] == '26/09/2023']
# df.to_csv('Rain.csv', index=False)

In [68]:
# import pandas as pd 

# df = pd.read_csv('LATLONONLY.csv')

# df['Target'] = 1
# df.to_csv('LATLONONLY.csv', index =False)

In [69]:
# import pandas as pd
# df = pd.read_csv('LATLONLY.csv')
# df = df[['lat', 'lon', 'NDVI', 'slope', 'Target']]
# df.to_csv('LATLONLY.csv', index = False)


In [70]:
# import pandas as pd 
# df = pd.read_csv('Luan.csv')

# df.drop(['lat_y', 'lon_y'], axis = 1, inplace = True)
# df = df[['lat_x', 'lon_x', 'NDVI', 'slope']]
# df = df.rename({'lat_x': 'lat', 'lon_x': 'lon'}, axis = 1)
# df.to_csv('lat_lon_NDVI_slope.csv', index = False)

# Training model RandomForest Classifier

In [71]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('Thu.csv')

X = df.iloc[0:45664, 2:5 ]

y = df.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 22324)

clf = RandomForestClassifier(criterion = 'gini', n_estimators = 1000, max_depth = 10, min_samples_split = 10, random_state = 1)
# max_depth = The maximum depth of the tree. If None, then nodes are expanded until all leaves are pure or until all leaves contain less than min_samples_split samples.
# min_samples_split = The minimum number of samples required to split an internal node:
# random_state = Controls both the randomness of the bootstrapping of the samples used when building trees (if bootstrap=True) 
# and the sampling of the features to consider when looking for the best split at each node

clf.fit(X_train, y_train)



RandomForestClassifier(max_depth=20, min_samples_split=10, n_estimators=1000,
                       random_state=1)

In [72]:
clf.feature_importances_

array([0.52504057, 0.46580442, 0.00915501])

In [73]:
df.columns

Index(['lat', 'lon', 'NDVI', 'slope', 'precipitation_sum (mm)', 'Target'], dtype='object')

In [74]:
y_pred = clf.predict(X_test)

In [75]:
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [76]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[6551,  207],
       [2236,  139]], dtype=int64)

In [77]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7325084857111573